USE customer_behaviour;
-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender,
       SUM(`purchaseamount(usd)`) AS total_revenue
FROM customer
GROUP BY gender;
-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customerid,
       `purchaseamount(usd)` AS purchase_amount
FROM customer
WHERE discountapplied = 'Yes'
  AND `purchaseamount(usd)` > (
        SELECT AVG(`purchaseamount(usd)`)
        FROM customer
      );
-- Q3. Which are the top 5 products with the highest average review rating?
SELECT itempurchased,
       AVG(reviewrating) AS avg_review_rating
FROM customer
GROUP BY itempurchased
ORDER BY avg_review_rating DESC
LIMIT 5;

SELECT * FROM customer_behaviour.customer;
-- Q4. Compare the average purchase amounts between Standard and Express Shipping.
select shippingtype,
  AVG(`purchaseamount(usd)`)
  from customer
  where shippingtype = 'Standard' or shippingtype ='Free Shipping'
  group by shippingtype;
  
  SELECT * FROM customer_behaviour.customer;
-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscriptionstatus,
  AVG(`purchaseamount(usd)`),sum(`purchaseamount(usd)`)
  from customer
  where subscriptionstatus = 'yes' or subscriptionstatus = 'No'
  group by subscriptionstatus;
  
    SELECT * FROM customer_behaviour.customer;
-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT itempurchased,
       SUM(
           CASE
               WHEN discountapplied='Yes'
               THEN 1
               ELSE 0
           END
       ) *100.0 / COUNT(*) AS discount_percentage
FROM customer
GROUP BY itempurchased
ORDER BY discount_percentage DESC
LIMIT 5;
SELECT * FROM customer_behaviour.customer;
-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
  select customer_segment,
		 count(*) as total_customers
  from
  (select
   case
	when previouspurchases<=2 then 'New'
    when previouspurchases<=7 then 'Returning'
    else 'Loyal'
  end as customer_segment
  from customer
  ) as temp
  group by customer_segment;
  SELECT * FROM customer_behaviour.customer;
-- Q8. What are the top 3 most purchased products within each category?
SELECT category,
       itempurchased,
       purchase_count
FROM
(
    SELECT category,
           itempurchased,
           COUNT(*) AS purchase_count,
           ROW_NUMBER() OVER (
               PARTITION BY category
               ORDER BY COUNT(*) DESC
           ) AS rn
    FROM customer
    GROUP BY category, itempurchased
) AS ranked
WHERE rn <= 3;
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscriptionstatus,
       COUNT(*) AS total_customers
FROM customer
WHERE previouspurchases > 5
GROUP BY subscriptionstatus;
-- Q10. What is the revenue contribution of each age group?
SELECT agegroup,
       SUM(`purchaseamount(usd)`) AS total_revenue
FROM customer
GROUP BY agegroup
ORDER BY total_revenue DESC;